id: segment_introduction
learningObjectives: 
- Learn what Segment is and how it works
hints:
- "Sign up here: https://app.segment.com/signup"
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Today we're going to connect our website to Segment."
      - text: "If you're not familiar with Segment, here's a brief rundown: it's a customer data platform that acts as a bus for event streams from your customer-facing applications."
      - text: "In addition, it builds customer profiles with the events so that you can get to know individual users' tendencies, even at massive scale, and personalize their experience with our brand."
      - text: "First step: let's create a free Segment workspace [here](https://app.segment.com/signup)."
      - text: "Once you've created your account, :instruction[come back here and let me know when you're ready to continue.]"
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Great job!"
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I'm here, just let me know when you're ready to continue."
