id: segment_destination
learningObjectives: 
- Learn how to connect source to destination in Segment

hints:
- "To connect a source to a destination, go to the catalog -> functions -> create function"
- "To perform a post request to the webhook url, you can use the `fetch` method. You can find more information about it in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)."
- "To put data in the fetch request use: `body: JSON.stringify({event: 'segment_destination'})`"

startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "OK, we have a source and some events, but we now need to connect it to a destination."
      - text: "A destination is a place where you can send your data to, like Google Analytics, Amplitude, or Mixpanel."
      - text: "We'll use a simple function as a destination. It will just log the events to the console."
      - text: "In this function, once we have a new track event, we'll log it to the console. But we also create a new post request to the webhook URL."
      - text: "This is the webhook url: https://engine.wilco.gg/users/${user.id}/event use post request with the following body: {\"event\": \"segment_destination\"}"
      - text: "Once you have it, :instruction[trigger the event using the register button]"

trigger:
  type: user_event
  params: 
    event: segment_destination
  flowNode:
    then:
      do:
      - actionId: bot_message
        params:
          person: keen
          messages:
          - text: "Awesome, we just manage to connect a source to a destination in Segment!"
      - actionId: finish_step
